teams = [
    {"name":"Real Madrid" ,  "pot":1 , "country":"Spain"},
    {"name":"Frankfurt" ,  "pot":1 , "country":"Germany"},
    {"name":"Man City" ,  "pot":1 , "country":"England"},
    {"name":"Milan",  "pot":1 , "country":"Italy"},
    {"name":"Bayern" ,  "pot":1 , "country":"Germany"},
    {"name":"Paris" ,  "pot":1 , "country":"France"},
    {"name":"Porto" ,  "pot":1 , "country":"Portogal"},
    {"name":"Ajax" ,  "pot":1 , "country":"Netherland"},

    {"name":"Liverpool" ,  "pot":2 , "country": "England"},
    {"name":"Chelsea" ,  "pot":2 , "country": "England"},
    {"name":"Tottenham" ,  "pot":2 , "country": "England"},
    {"name":"Atlético" ,  "pot":2 , "country": "Spain"},
    {"name":"Sevilla" ,  "pot":2 , "country": "Spain"},
    {"name":"Barcelona" ,  "pot":2 , "country":"Spain"},
    {"name":"Leipzig" ,  "pot":2 , "country":"Germany"},
    {"name":"Juventus" ,  "pot":2 , "country":"Italy"},
    
    {"name":"Dortmund" , "pot":3 , "country":"Germany"},
    {"name":"Internazionale" , "pot":3 , "country":"Italy"},
    {"name":"Napoli" , "pot":3 , "country":"Italy"},
    {"name":"Leverkusen" , "pot":3 , "country":"Germany"},
    {"name":"Sporting CP" , "pot":3 , "country":"Portogal"},
    {"name":"Benfica" , "pot":3 , "country":"Portogal"},
    {"name":"Shakhtar" , "pot":3 , "country":"Ukrane"},
    {"name":"Salzburg" , "pot":3 , "country":"Austria"},

    {"name":"Rangers" , "pot":4 , "country":"Scotland"},
    {"name":"Dinamo Zagreb" , "pot":4 , "country":"Croatia"},
    {"name":"Marseille" , "pot":4 , "country":"France"},
    {"name":"København" , "pot":4 , "country":"Denmark"},
    {"name":"Club Brugge" , "pot":4 , "country":"Belgium"},
    {"name":"Celtic" , "pot":4 , "country":"Scotland"},
    {"name":"Plzeň" , "pot":4 , "country":"Czech Republic"},
    {"name":"M Haifa" , "pot":4 , "country":"Not Found"},
]
